kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: host
  user:
    from_secret: username
  password:
    from_secret: password

steps:
- name: deploy
  environment:
  commands:
    - docker compose -f docker-compose-deploy.yml build
    - docker compose -f docker-compose-deploy.yml up -d

trigger:
  branch:
  - main
  

