kind: pipeline
name: build

steps:
- name: build 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.oldmanz.com/llm_map/ollama
    registry: registry.oldmanz.com
    context: ollama
    dockerfile: ollama/Dockerfile
    tags:
    - latest
    
trigger:
  branch:
  - main


kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: host
  user:
    from_secret: username
  password:
    from_secret: password

steps:
- name: deploy
  environment:
    DOCKER_USERNAME: 
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - echo $DOCKER_PASSWORD | docker login registry.oldmanz.com --username $DOCKER_USERNAME --password-stdin
    - docker compose -f docker-compose-deploy.yml up -d

trigger:
  branch:
  - main
  

